{% set version = "0.3.3" %}

package:
  name: local-lua-debugger-vscode
  version: {{ version }}

source:
  url: https://github.com/tomblind/local-lua-debugger-vscode/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 42c05e715708dae3e31f2039a1ac87a7964585b036d5d4fada4b3e097dca719d

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - local-lua-dbg &
    - exe_pid=$!
    - "trap \"kill -SIGTERM ${exe_pid}\" SIGTERM"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Local Lua Debugger
  home: https://github.com/tomblind/local-lua-debugger-vscode
  dev_url: https://github.com/tomblind/local-lua-debugger-vscode

extra:
  recipe-maintainers:
    - danielnachun
